### ISSUE TITLE
Edge not being rendered

### ISSUE THREAD

**Issue by chirag-thirstydevs** [Azim-Ahmed/Automation-workflow#1]
Have you tried this with backend API integration 
I am facing issue if I integrate with API then edge is not being rendered and if I remove API Integration then it is working perfectly fine.

**Comment by Azim-Ahmed** [comment]
You need to send the edges data to the backend. I worked with websocket. and it's totally fine

**Comment by chirag-thirstydevs** [comment]
Yes thanks.

**Comment by chirag-thirstydevs** [comment]
* {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        }
    



   Hello,Azim-Ahmed I hope you are having a great experience from our support agent .We would love to hear honest feedback on your experience on support for ticket #PL-1700736.Share your review here

**Comment by Azim-Ahmed** [comment]
Sorry, How did I get support from your support agent?
